name: Deploy Quartz to GitHub Pages

on:
  push:
    branches:
      - v4  # Change this if your main branch has a different name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm' # Optional: Speeds up dependency installation

      - name: Install Dependencies
        run: npm install

      - name: Build Quartz site
        run: npx quartz build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Quartz outputs to "public" by default

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
